### ISSUE TITLE
Bot freezing and staying in corner after X amount of damage

### ISSUE THREAD

**Issue by xLeviNx** [jeefo/yapb#162]
Bots tend to freeze after they take an X amount of damage, and begin to sit in a corner. Running the latest version of yapb

**Comment by jeefo** [comment]
Too little info. Map, situation, mods. Probably demo needed.

**Comment by xLeviNx** [comment]
Running Zombie Hell (Custom Mod)
Occurs on all maps
Last player is a boss zombie. Boss zombie gets roughly 5000+ hp depending on the level. When player's do X amount of damage, the bot stays into a corner and does not move, unless a player gets close enough, but rarely does it move. I can send a demo this weekend

**Comment by jeefo** [comment]
Affirmative)

yb_check_enemy_rendering  - Allows bots for i.e. CSDM (spawn protection) when players are glowed, bots skip this players, since they can't be hurt.

yb_stab_close_enemies  - Prevents bots from using knife in close range attacks. It's useful for mods when knife is not available to use (stripped from inventory).

Please, try 482 commit (should be ready in a few minutes).

If problem persists please, pack you addon folder (without passwords ofc), and send archive to ds@stx.su. Bots are not admin plugins, they  making decisions, and it's really hard hunt down AI bugs with custom mods without having actual setup.

Thank you,

**Comment by xLeviNx** [comment]
So far it looks like it is working fine. Will continue to test and keep you updated if any other issues begin to happen.
