### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by GhostRander** [jeefo/yapb#79]
I liked those yapb bots but I see that they do not use the silencers, flashlight and night vision
and I see that the bot chatter of the csbot no longer works

**Comment by Left4Dad** [comment]
Yes, we needed this features on yapb bots. And also add more waypoints like 3000 waypoints or more. Or make it unlimited. 1024 is not enough for some maps. Make a command for them to have the ability to use flashlight or not. And make some bits use silencer. Dont make them always using it

**Comment by jeefo** [comment]
They do use silencers actually. From time to time.

As for night vision and flashlight, it's useless, as engine doesn't give lighting info for given point easy way, so they can use it randomly, if you need it.

Podbotmm has code for calculating lighting info, but it's too cpu-intensive to include it into yapb. Sorry.

**Comment by Left4Dad** [comment]
I am pretty sure they didnt use silencer. I have played with yapb so many times. And i mean so many times! But never see them use silencers at all.

If you think that u cant add flashlight, than forget about this idea. But i really want it :)



plz add these:

1)make mp_freeforall 1 and 0 works with yapb.

2)yapb bots use silencer. But dont let them use silencer every time. Make it random. Make the percent of using silencer as 50% chances. Or make a command that allow or disallow yapb to use silencer. Here is an example: yb_silencer 0 / yb_silencer 1

3)Third, plz fix issue for low-difficulty bots because they never try to defuse the bomb.

4)the lowest difficulty 0 and 1 bots will not throw grenades, plz let them throw grenades.

5)Let yapb bots use flashlight on dark areas. Add a command : yb_allow_flashlight 1 / yb_allow_flashlight 0. (If u can add this, it will be great)

6) add 3048 points. Need lots of waypoints for larger maps. If 2048 is the max u can do...than go for 2048 than :)

7) Can u make bots buy any pistols they want on the first round? They never bought any pistols. They only buy it if they have a rifle :(
You can do this: If yb_economics rounds 0, can buy any pistols on first round. and yb_economics_rounds 1, they wont buy pistols on first round. ( Follow economics cfg).
 
Or u can make a new cfg for yapb when they use economics and when they do not use economics. Make two cfgs.

 
8)[Mention on Above ] for yb_difficulty 0 and 1, the bots are already kinda good. For difficulty 2 to 4 is extremely pro like they are cheating. For difficulty 2, can u make them react slower abit? And also make the difficulty 2 bots not to aim so well. Difficulty 2 is already like playing against professional level. It is very hard due to the bots have aimbot and can immediately kill you cuz they always aim for the head. For difficulty 0,1,2,3, can you make them have shaky aim? So that the bots dont play like a aimbot hacker. Maybe you can make them aim below the head or make their aim abit shaky.

BTW, Do u have any social media so that i can talk to u??

I hope u understand these suggestions i gave u because i have played with yapb for almost a year. And i hope to see my suggestions being added :)

Make it on pc and android :D

**Comment by jeefo** [comment]
1) done
2) done
3) need to test
4) done (but less than hs bots)
5) will try to add without impact on perfomance, need some time.
6) 2048 added
7) probably, not sure now
8) aimbot is cool, however will tweak difficulties in some time.

android build delaying. sorry.

**Comment by Left4Dad** [comment]
Thanks for making these. But i played on android. Can u try to make it faster for android? :(

**Comment by jeefo** [comment]
@Left4Dad 

On what map do you play where you need flashlights?

**Comment by Left4Dad** [comment]
Hmm it depends on some maps that needed flashlights. For example, Dust l, cs_747 (forgot the name), Nuke, And other custom made maps. Hmm, if its hard, i suggest u dont add flashlights than :)

**Comment by jeefo** [comment]
Flashlight and nvg already working in current build.

**Comment by Left4Dad** [comment]
You mean for yapb?

**Comment by jeefo** [comment]
Yup

**Comment by Left4Dad** [comment]
So u added the function?? Cool! I was hoping u can do all those suggestions on android tho. Do it as quick as you can :)

**Comment by jeefo** [comment]
https://yapb.ru/files/android/cstrike/5592/

Google Play version of Xash3D & CS16client should be uninstalled before try. Probably android debugging should be enabled to make those APKs.

It's temporary, just for test. Changes will be published to CS16client with next update.

**Comment by Left4Dad** [comment]
Wow thanks! I will try it on and tell you if it works perfectly :)

**Comment by jeefo** [comment]
https://yapb.ru/files/android/cstrike/5594/

friendlyfire should be 1, after setting mp_freeforall -> sv_restart 1 should work.

about blood and bullets, dunno actually. this is just a test build, have no time to debug anything atm.

**Comment by Left4Dad** [comment]
So will all these yapb features be in the official apk cs 16client apk on play store???

About the mp_freeforall. I will try now to see if it works

**Comment by jeefo** [comment]
Sure, changes will be available in official client, when all testing will be finished.

**Comment by Left4Dad** [comment]
I tried. It didnt work. I go to game and set friendly fire on. Than when i enter a map, the yapb bots automatic spawn in. And i set mp_freeforall 1 and type sv_restart 1. When the match restart, my team still ignore each other and try to kill enemies. They didnt kill their own teammates. Can plz help? Have u tried urself in the apk and does it work?

**Comment by jeefo** [comment]
Tried. And it's works correctly. Show yb version output.

**Comment by Left4Dad** [comment]
How to show yb version output?

**Comment by Left4Dad** [comment]
Do you have facebook messenger? Easier to talk using it.

**Comment by Left4Dad** [comment]
I type yb_version and its 2.10. Only problem is that mp_freeforall 1 didnt work :(

Is there other yapb commands i must use to make them shoot each other??

**Comment by Left4Dad** [comment]
Ok it works now. Thank u so much bro!!! U helped out alot :). I will close this issue now. Hope u add these features in official apk soon :D

**Comment by Left4Dad** [comment]
Here are the final things that should be added and fix so that yapb will be more fun and making it look realistic. [YAPB WILL BE BETTER]

1) When yapb bots zoom using snipers, and when the bot using sniper saw the enemy and when the enemy left their sight, the bots unzoom the scope too fast. Its not realistic. Plz make them zoom abit longer before unzooming. Make it 2secs before unzooming the sniper.

2) Make afk yapb bots. I know this sounds dumb, but its a cool feature. There is once i played yapb and there is a bot in my team that goes afk. Its so realistic. Maybe its a bug. But can you add this plz??? Its fun. Add this function using a command like for example, yb_afk 0 means all bots will not be afk, and yb_afk 1 means bots sometimes goes afk. Make the max number of 1-3 bots that goes afk. And make it super random and very rare. Hope u can add this. And remember, make it rarely happen.

3) Make bots balance themselves using all grenades. Yapb bots prefer smoke grenade more. Plz balance it so that they can use other grenades better.

4)Plz add yb_debug 2. The ones that work is yb debug 0 and 1. Can u make another one? Which is yb_debug 2. Make yb_debug 2 only show these features (Name, Health, Armor, Item, Clip, Ammo and money). Thats all. Dont add the viewable waypoints where the yapb will walk to certain places with a line that they will follow just like in yb_debug 1. Add a yb_debug 2 with only those things plzz.
Yb_debug 1 is too complicated.

5)Make the yapb always listen to our commands for [Drop C4, Drop weapon,  and Make double jump] Sometimes yapb will not drop the c4 or weapons when i use those commands. Make them 100% listen to what we want them to do. And also make them come to where i stand and make a double jump. Sometimes they stand at the wrong position for the double jump and sometimes they ignore to do the double jump and walked away.

6) Make yapb bots look around while in spawn. This can make it look realistic. In cs1.6 normal bots, they will look at different positions while freezing at spawn. But those bots only look at one direction. Thats all. But for yapb, when they spawn, they only look straight forward and all yapb bots stand in a line like a soldier 😂. Make 1 to 4 bots to look around when they spawn. So that they look like humans. Make them look at different places while freezing at spawn. Make a command for this if possible. Make two commands like, one will make them not look around in spawn, another will make them look around the area while freezing at spawn. Make it random. Dont make all 4 bots to look around. Make some bots to look around and not all the bots.

7)Can u make the commands to dissapear when we click these commands? Like Drop c4, drop weapon, double jump and finish double jump. Here is my problem. When i click drop c4 or double jump, the commands 1,2,3,4 is still there. We must click 0 to exit the commands. Can u make it more simplier?? Do it this way: if i clicked on 1 or 2 or 3 or 4, the yapb action commands will disapear by itself so that i dont need to press 0 to exit the yapb action commands . This way is much more faster. Plz do it :)

8) [This is an optional idea]. Since that all yapb bots has aimbot, can u make two seperate commands for two seperate bot playstyle? For example, yb_aimbot 1 means they will play like the way they play right now. They uses aimbots. And another command is yb_aimbot 0 that will disable them to aimlock at their enemies and they will only shoot the enemy if they see their enemy. Plz make these. Its more realistic. For example like cs 1.6 normal bots, they dont have aimbot. So when we go behind our enemy, they wont see us. But for yapb, they will always know where we are😂. So plz add these two commands whether they will use aimbot or will not use aimbot. [This is optional. If u can do this, it will make us have better gameplay experience with yapb bots]

9) Make a command for yapb to use or not to use night vision and flashlight. Because i played the apk version that u send me. I see those bots use night vision. But i didnt see them use flashlight yet because i only play for 10 mins. Can u tell me they will use flashlight or not? And have u added any commands for them to allow or disallow to use flashlight and night vision?? Please add commands in the yapb.cfg file or u can add the ability to buy or not to buy night vsion on the general.cfg file.


THANK YOU ONCE AGAIN. YOU HAVE MADE YAPB BETTER EVERY SINGLE TIME!
If u dont understand my requests, feel free to ask me as well. I just want yapb to be realistic and better :)

**Comment by Left4Dad** [comment]
So can you implement these features?

**Comment by Left4Dad** [comment]
?? Have u gone on vacation?😅
