### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by PRinceBhai** [jeefo/yapb#90]
1. CT bots will not defuse the bomb 7/10 times. (They just keep going back and forth even tho there's plenty of time to defuse and all of the enemy team is dead, 7 being the amount of no defuses)
2. Some time on certain maps bots keep jumping from one point to another.

3. Bots are using maps textures as decals. This is fixed on release "yapb-2.8.4766-dev-git322-windows".
Edit : This isn't a bug with yapb. My decals.wad was corrupt. Sorry.

4. Same as #1 but sometimes 5/10 T bots will not plant the bomb even tho there are teammates with them on the bomb site and will leave the bomb site to rotate to the other one which results in level fail. (Timeout/Killed)
5. (I've even posted it before) "they still spam radio chatter messages" as on release "yapb-2.9.5395-dev-git341-windows".

**Comment by jeefo** [comment]
Hello.

1,4,5 should be fixed here: https://transfer.sh/Ij8Ts/yapb.dll Can you verify?

About 2. Can you provide demo ?

NOTE: This build is uses new waypoint format, if you want to use your old waypoints you should set yb_graph_url cvar to "" to force bot dll to convert existing PWF instead of downloading one from waypoint database.

**Comment by jeefo** [comment]
No feedback.

**Comment by PRinceBhai** [comment]
Hi, and uh sorry i didn't reply since i left cs modding and stuff for a while. But i just wanted to get back and check stuff. So if you can then please re upload the dll or point me to a new one. So that i can check it again. Thanks.
